# Generated by Django 4.1.5 on 2023-05-18 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_patient_profile_gender_profile_phone_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="patient",
            new_name="Patients",
        ),
    ]
