# Generated by Django 4.1.5 on 2023-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_rename_patients_patient_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.CharField(default="", max_length=200),
        ),
    ]
