# Generated by Django 4.1.5 on 2023-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_patient_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(default="", max_length=200),
        ),
    ]
