# Generated by Django 4.1.5 on 2023-05-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_patient_gender_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="state",
        ),
        migrations.AddField(
            model_name="profile",
            name="cnic",
            field=models.CharField(default="33100-7947702-1", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="designation",
            field=models.CharField(
                default="Therapist/Rehabilitationist", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="province",
            field=models.CharField(default="e.g Punjab", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="Your address", max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(default="Pakistan", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(default="Your Academical status", max_length=400),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(default="Male/Female", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(default="e.g 38000", max_length=200),
        ),
    ]
