# Generated by Django 4.1.5 on 2023-05-22 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_profile_state_profile_cnic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+923111234567'. 11 digits required.",
                        regex="^\\+?\\d{11}$",
                    )
                ],
            ),
        ),
    ]
