# Generated by Django 4.1.5 on 2023-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_profile_additional_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="image",
            field=models.ImageField(default="image", upload_to="images/"),
            preserve_default=False,
        ),
    ]
