# Generated by Django 4.1.5 on 2023-05-28 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_section_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
